name: Calculadora Python - PR

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar requirements
      working-directory: code/Python
      run: |
        pip install -r requirements.txt

    - name: Run linters (flake8)
      working-directory: code/Python
      continue-on-error: true
      run: |
        flake8 .

    - name: Run security checks (bandit)
      working-directory: code/Python
      run: |
        bandit -r .
