name: Calculadora Python - PR

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: code/Python
      run: |
        pip install -r requirements.txt
        pip install flake8 bandit

    - name: Run linters
      working-directory: code/Python
      run: |
        flake8 .

    - name: Run security checks
      working-directory: code/Python
      run: |
        bandit -r .
